package comp3350.plarty.objects;

import android.support.annotation.NonNull;
import org.joda.time.DateTime;

/**
 * RecurringEvent Class is generated by RecurringEventGenerator class
 * to fill a schedule.
 * It contains a pointer to the parent which created it,
 * to aid with altering generation.
 */
public class RecurringEvent extends Event {
    private final RecurringEventGenerator parent;

    public RecurringEvent(String name, int id, User organiser, String location, DateTime startDate, DateTime endDate, RecurringEventGenerator parent) {
        super(name, id, organiser, location, startDate, endDate);
        ObjectValidator.nullCheck(parent, "CurrentEventParent");
        this.parent = parent;
    }

    public RecurringEventGenerator getParent() {
        return this.parent;
    }

    /**
     * Child events all share an id with their parent, so they should only
     * be considered equal if they occur on the same date/time.
     */
    @Override
    public boolean equals(Object object) {
        return object instanceof RecurringEvent &&
                super.equals(object) &&
                this.getInterval().equals(((RecurringEvent) object).getInterval());
    }

    @NonNull
    public String toString() {
        return super.toString() + "\n Instance of " + parent.getName() + " at " + getStart() + " to " + getEnd();
    }
}
